name: Build and Package Cleaner DEB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pyqt5 python3-setuptools xfsprogs btrfs-progs curl binutils
          pip3 install pyinstaller

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build executable with PyInstaller (onedir mode)
        run: |
          pyinstaller --onedir --windowed --name cleaner cleaner.py

      - name: Prepare DEB package structure
        run: |
          rm -rf pkg
          mkdir -p pkg/DEBIAN
          mkdir -p pkg/usr/local/cleaner
          mkdir -p pkg/usr/local/bin
          mkdir -p pkg/usr/share/applications

          # Copy entire build directory
          cp -r dist/cleaner/* pkg/usr/local/cleaner/

          # Create launcher script
          echo -e "#!/bin/bash\n/usr/local/cleaner/cleaner" > pkg/usr/local/bin/cleaner
          chmod +x pkg/usr/local/bin/cleaner

          # Create control file
          cat << 'EOF' > pkg/DEBIAN/control
          Package: cleaner
          Version: 0.0.1-alpha
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: python3, python3-pyqt5, xfsprogs, btrfs-progs, docker.io, flatpak
          Maintainer: darkcrusader002@gmail.com
          Description: Cross-Platform Cleaner GUI application
           Приложение для очистки временных файлов, кэша браузеров, дефрагментации,
           управления планировщиком, отправки уведомлений по Email и Slack.
          EOF

          # Create desktop entry
          cat << 'EOF' > pkg/usr/share/applications/cleaner.desktop
          [Desktop Entry]
          Name=Cleaner
          Comment=Cross-Platform System Cleaner
          Exec=/usr/local/bin/cleaner
          Icon=utilities-terminal
          Terminal=false
          Type=Application
          Categories=Utility;
          EOF

      - name: Manually build DEB with gzip (for compatibility with older systems)
        run: |
          mkdir -p build-deb
          cd pkg
          tar -czf ../build-deb/control.tar.gz -C . DEBIAN
          tar -czf ../build-deb/data.tar.gz -C . usr
          cd ../build-deb
          echo '2.0' > debian-binary
          ar cru cleaner_0.0.1-alpha_amd64.deb debian-binary control.tar.gz data.tar.gz
          cp cleaner_0.0.1-alpha_amd64.deb ../

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: cleaner-deb
          path: cleaner_*.deb

      - name: Upload DEB to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: cleaner_*.deb
