name: Build and Package Cleaner DEB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Install system packages for packaging
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pyqt5 python3-pip python3-setuptools xfsprogs btrfs-progs

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name cleaner cleaner.py

      - name: Prepare DEB package structure
        run: |
          rm -rf pkg
          mkdir -p pkg/DEBIAN
          mkdir -p pkg/usr/local/bin
          mkdir -p pkg/usr/share/applications

          # Copy binary
          cp dist/cleaner pkg/usr/local/bin/cleaner
          chmod 755 pkg/usr/local/bin/cleaner

          # Create control file
          cat << 'EOF' > pkg/DEBIAN/control
          Package: cleaner
          Version: 0.0.1 alfa
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: python3, python3-pyqt5, xfsprogs, btrfs-progs, docker.io, flatpak, snapd
          Maintainer: darkcrusader002@gmail.com
          Description: Cross-Platform Cleaner GUI application
           Приложение для очистки временных файлов, кэша браузеров, дефрагментации,
           управления планировщиком, отправки уведомлений по Email и Slack.
          EOF

          # Create desktop entry
          cat << 'EOF' > pkg/usr/share/applications/cleaner.desktop
          [Desktop Entry]
          Name=Cleaner
          Comment=Cross-Platform System Cleaner
          Exec=/usr/local/bin/cleaner
          Icon=utilities-terminal
          Terminal=false
          Type=Application
          Categories=Utility;
          EOF

      - name: Build DEB
        run: |
          dpkg-deb --build pkg cleaner_${{ github.sha }}.deb

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: cleaner-deb
          path: cleaner_*.deb
