name: Build and Package Cleaner DEB

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pyqt5 python3-pip python3-setuptools xfsprogs btrfs-progs flatpak snapd

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name cleaner cleaner.py

      - name: Prepare DEB package structure
        run: |
          rm -rf pkg/
          mkdir -p pkg/DEBIAN pkg/usr/local/bin pkg/usr/share/applications
          cp dist/cleaner pkg/usr/local/bin/cleaner || echo "Binary not found!"
          chmod 755 pkg/usr/local/bin/cleaner || true

          # Write control file
          echo "Package: cleaner" > pkg/DEBIAN/control
          echo "Version: 0.0.1-alpha" >> pkg/DEBIAN/control
          echo "Section: utils" >> pkg/DEBIAN/control
          echo "Priority: optional" >> pkg/DEBIAN/control
          echo "Architecture: amd64" >> pkg/DEBIAN/control
          echo "Depends: python3, python3-pyqt5, xfsprogs, btrfs-progs, flatpak, snapd" >> pkg/DEBIAN/control
          echo "Maintainer: darkcrusader002@gmail.com" >> pkg/DEBIAN/control
          echo "Description: Cross-Platform Cleaner GUI application" >> pkg/DEBIAN/control
          echo " Приложение для очистки временных файлов, кэша браузеров, дефрагментации," >> pkg/DEBIAN/control
          echo " управления планировщиком, отправки уведомлений по Email и Slack." >> pkg/DEBIAN/control

          # Write desktop entry
          echo "[Desktop Entry]" > pkg/usr/share/applications/cleaner.desktop
          echo "Name=Cleaner" >> pkg/usr/share/applications/cleaner.desktop
          echo "Comment=Cross-Platform System Cleaner" >> pkg/usr/share/applications/cleaner.desktop
          echo "Exec=/usr/local/bin/cleaner" >> pkg/usr/share/applications/cleaner.desktop
          echo "Icon=utilities-terminal" >> pkg/usr/share/applications/cleaner.desktop
          echo "Terminal=false" >> pkg/usr/share/applications/cleaner.desktop
          echo "Type=Application" >> pkg/usr/share/applications/cleaner.desktop
          echo "Categories=Utility;" >> pkg/usr/share/applications/cleaner.desktop

      - name: Debug DEB folder structure
        run: |
          echo "Listing pkg directory:"
          find pkg/
          echo
          echo "Control file contents:"
          cat pkg/DEBIAN/control

      - name: Build DEB
        run: |
          dpkg-deb --build pkg cleaner_${{ github.sha }}.deb

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: cleaner-deb
          path: cleaner_*.deb
